name: lib5_crypto_implementation_dart
description: A crypto implementation for lib5 in Dart.
version: 1.0.0
repository: https://github.com/s5-dev/lib5_crypto_implementation_dart

environment:
  sdk: ^3.0.0

dependencies:
  cryptography: ^2.3.0
  lib5: ^0.1.0
  thirds: ^0.2.0-alpha.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
