name: lib5_crypto_implementation_dart
description: A crypto implementation for lib5 in Dart.
version: 0.2.0
repository: https://github.com/s5-dev/lib5_crypto_implementation_dart

environment:
  sdk: ^3.0.0

dependencies:
  cryptography_plus: ^2.7.0
  cryptography_flutter_plus: ^2.3.2
  lib5: 
    git: 
      url: https://github.com/lukehmcc/lib5.git
      ref: 0.2.0-patched

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
